# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac9588890839b0c218645109ae8802a61d18d7d9e9b71eb9afa106d51e211c589bb455cb3233f304356e10ff340ef54fde1a0b956f584a111aa7e44fee5d034f

test:
  secret_key_base: 916a9ad7d05e310e3f1f1bab40901f53f5f4d5ee355898f9bb3bd98bdf7d57ba4ffe1355d101348903d51684bdb7127bf855b415ad21a44a4bdca46c96f9bb98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
